// --- State Management ---
const state = {
    pc: null,
    dataChannel: null,
    isHost: false,
    username: localStorage.getItem('username') || 'Anonymous',
    theme: localStorage.getItem('theme') || 'light'
};

// --- DOM Elements ---
const screens = {
    welcome: document.getElementById('welcome-screen'),
    conn: document.getElementById('connection-screen'),
    chat: document.getElementById('chat-screen')
};

const configuration = {
    iceServers: [{ urls: 'stun:stun.l.google.com:19302' }]
};

// --- Initialization ---
document.addEventListener('DOMContentLoaded', () => {
    initTheme();
    setupEventListeners();
});

function setupEventListeners() {
    document.getElementById('btn-create-room').onclick = startHost;
    document.getElementById('btn-join-room').onclick = startGuest;
    document.getElementById('btn-send').onclick = sendMessage;
    document.getElementById('theme-toggle').onclick = toggleTheme;
    document.getElementById('btn-settings').onclick = () => document.getElementById('settings-modal').classList.remove('hidden');
    document.getElementById('close-settings').onclick = saveSettings;

    // Handle "Enter" key in input
    document.getElementById('msg-input').onkeypress = (e) => {
        if(e.key === 'Enter') sendMessage();
    };
}

// --- WebRTC Logic ---

async function createPeerConnection() {
    state.pc = new RTCPeerConnection(configuration);

    state.pc.onicecandidate = (event) => {
        if (!event.candidate) {
            // ICE Gathering finished, generate QR
            const sdpData = btoa(JSON.stringify(state.pc.localDescription));
            displayQR(sdpData);
        }
    };

    state.pc.ondatachannel = (event) => {
        setupDataChannel(event.channel);
    };
}

function setupDataChannel(channel) {
    state.dataChannel = channel;
    state.dataChannel.onopen = () => onConnectionSuccess();
    state.dataChannel.onmessage = (e) => handleIncomingMessage(JSON.parse(e.data));
}

// --- Hosting Workflow ---
async function startHost() {
    state.isHost = true;
    showScreen('conn');
    document.getElementById('step-1-offer').classList.remove('hidden');
    
    await createPeerConnection();
    state.dataChannel = state.pc.createDataChannel("chat");
    setupDataChannel(state.dataChannel);

    const offer = await state.pc.createOffer();
    await state.pc.setLocalDescription(offer);
}

// --- Joining Workflow ---
function startGuest() {
    state.isHost = false;
    showScreen('conn');
    document.getElementById('step-2-join').classList.remove('hidden');

    const scanner = new Html5QrcodeScanner("qr-reader", { fps: 10, qrbox: 250 });
    scanner.render(async (decodedText) => {
        scanner.clear();
        document.getElementById('step-2-join').classList.add('hidden');
        await handleOfferScan(decodedText);
    });
}

async function handleOfferScan(encodedSdp) {
    await createPeerConnection();
    const offer = JSON.parse(atob(encodedSdp));
    await state.pc.setRemoteDescription(offer);
    
    const answer = await state.pc.createAnswer();
    await state.pc.setLocalDescription(answer);
    
    document.getElementById('step-3-answer').classList.remove('hidden');
    // QR will be generated by onicecandidate logic
}

// Host scans guest's answer
document.getElementById('btn-scan-answer').onclick = () => {
    document.getElementById('step-1-offer').classList.add('hidden');
    document.getElementById('step-2-join').classList.remove('hidden');
    
    const scanner = new Html5QrcodeScanner("qr-reader", { fps: 10, qrbox: 250 });
    scanner.render(async (decodedText) => {
        scanner.clear();
        const answer = JSON.parse(atob(decodedText));
        await state.pc.setRemoteDescription(answer);
    });
};

// --- Messaging Logic ---

function sendMessage() {
    const input = document.getElementById('msg-input');
    const text = input.value.trim();
    if (!text || !state.dataChannel) return;

    const msgObj = {
        type: 'text',
        content: text,
        sender: state.username,
        time: new Date().toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})
    };

    state.dataChannel.send(JSON.stringify(msgObj));
    appendMessage(msgObj, 'sent');
    input.value = '';
}

function handleIncomingMessage(msg) {
    if (msg.type === 'text') {
        appendMessage(msg, 'received');
        vibrateDevice();
        playNotificationSound();
    }
}

function appendMessage(msg, side) {
    const container = document.getElementById('chat-messages');
    const div = document.createElement('div');
    div.className = `message ${side}`;
    div.innerHTML = `
        <div class="msg-sender">${msg.sender}</div>
        <div class="msg-content">${sanitize(msg.content)}</div>
        <div class="msg-time">${msg.time}</div>
    `;
    container.appendChild(div);
    container.scrollTop = container.scrollHeight;
}

// --- Helpers ---

function showScreen(screenKey) {
    Object.values(screens).forEach(s => s.classList.remove('active', 'hidden'));
    Object.keys(screens).forEach(key => {
        if(key !== screenKey) screens[key].classList.add('hidden');
    });
    screens[screenKey].classList.add('active');
}

function displayQR(data) {
    const container = state.isHost ? 'qrcode-container' : 'qrcode-answer-container';
    document.getElementById(container).innerHTML = "";
    new QRCode(document.getElementById(container), {
        text: data,
        width: 256,
        height: 256,
        correctLevel: QRCode.CorrectLevel.L
    });
}

function onConnectionSuccess() {
    showScreen('chat');
    vibrateDevice();
}

function sanitize(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

function toggleTheme() {
    state.theme = state.theme === 'light' ? 'dark' : 'light';
    document.body.className = state.theme + '-mode';
    localStorage.setItem('theme', state.theme);
}

function initTheme() {
    document.body.className = state.theme + '-mode';
}

function saveSettings() {
    state.username = document.getElementById('username-input').value || 'Anonymous';
    localStorage.setItem('username', state.username);
    document.getElementById('settings-modal').classList.add('hidden');
}

function vibrateDevice() {
    if ("vibrate" in navigator) navigator.vibrate(100);
}

function playNotificationSound() {
    const audio = new Audio('https://assets.mixkit.co/active_storage/sfx/2354/2354-preview.mp3');
    audio.play().catch(() => {});
}
